version: '3.7'

services: 
  server.api:
      container_name: nest-elastic-api
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      ports:
        - 3000:3000
